import AuthProvider from "@/components/AuthProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { IconContext } from "react-icons";
import toast, { Toaster } from "react-hot-toast";
import { UserProvider } from "./UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <AuthProvider>
            <UserProvider>
              <Toaster />
              {children}
            </UserProvider>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
